site_name: platform-ng
repo_url: https://github.com/pkorobeinikov/platform-ng
repo_name: pkorobeinikov/platform-ng
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  logo: asset/platform-icon.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: red
      accent: red
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb-outline
        name: Тёмная тема
    - scheme: slate
      primary: red
      accent: grey
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb
        name: Светлая тема
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - footnotes
  - meta
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
nav:
  - В начало: index.md
  - Для разработчиков сервисов:
      - Введение: service-developer/index.md
  - Для разработчиков платформы:
      - Введение: platform-developer/index.md
      - ADR:
          - 1. Record architecture decisions: platform-developer/adr/0001-record-architecture-decisions.md
  - Для devops:
      - Введение: devops/index.md
  - Образцовые подходы:
      - Введение: best-practice/index.md
      - Postgres: best-practice/postgres.md
      - Observability: best-practice/observability.md
